[package]
name = "wasm-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4"
wasm-bindgen = "0.2"
wasm-logger = "0.2.0"

[dependencies.web-sys]
version = "0.3.22"
features = [
  "console"
]
